export const CLIENT_ACTION_TYPES = {
  SET_CLIENTE_INFO: "client/SET_CLIENT_INFO",
  SET_CLIENT_LIST: "client/SET_CLIENT_LIST",
  SET_CLIENTE_ADD: "client/SET_CLIENT_ADD",
  SET_CLIENTE_DEL: "client/SET_CLIENT_DEL",
};
